In [1]:
import pandas as pd
import seaborn as sn
import matplotlib.pyplot as plt

In [4]:
dataSet = pd.read_csv("./SAheart.data")

print(dataSet.head(5))
print(dataSet.info())
print(dataSet.describe())
type(dataSet)
print(dataSet.columns)
print(dataSet.transpose())
print(dataSet.shape)

   row.names  sbp  tobacco   ldl  adiposity  famhist  typea  obesity  alcohol  \
0          1  160    12.00  5.73      23.11  Present     49    25.30    97.20
1          2  144     0.01  4.41      28.61   Absent     55    28.87     2.06
2          3  118     0.08  3.48      32.28  Present     52    29.14     3.81
3          4  170     7.50  6.41      38.03  Present     51    31.99    24.26
4          5  134    13.60  3.50      27.78  Present     60    25.99    57.34

   age  chd
0   52    1
1   63    1
2   46    0
3   58    1
4   49    1
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 462 entries, 0 to 461
Data columns (total 11 columns):
 #   Column     Non-Null Count  Dtype
---  ------     --------------  -----
 0   row.names  462 non-null    int64
 1   sbp        462 non-null    int64
 2   tobacco    462 non-null    float64
 3   ldl        462 non-null    float64
 4   adiposity  462 non-null    float64
 5   famhist    462 non-null    object
 6   typea      462 non-null    int64
 7   obesity    462 non-null    float64
 8   alcohol    462 non-null    float64
 9   age        462 non-null    int64
 10  chd        462 non-null    int64
dtypes: float64(5), int64(5), object(1)
memory usage: 39.8+ KB
None
        row.names         sbp     tobacco         ldl   adiposity       typea  \
count  462.000000  462.000000  462.000000  462.000000  462.000000  462.000000
mean   231.935065  138.326840    3.635649    4.740325   25.406732   53.103896
std    133.938585   20.496317    4.593024    2.070909    7.780699    9.817534
min      1.000000  101.000000    0.000000    0.980000    6.740000   13.000000
25%    116.250000  124.000000    0.052500    3.282500   19.775000   47.000000
50%    231.500000  134.000000    2.000000    4.340000   26.115000   53.000000
75%    347.750000  148.000000    5.500000    5.790000   31.227500   60.000000
max    463.000000  218.000000   31.200000   15.330000   42.490000   78.000000

          obesity     alcohol         age         chd
count  462.000000  462.000000  462.000000  462.000000
mean    26.044113   17.044394   42.816017    0.346320
std      4.213680   24.481059   14.608956    0.476313
min     14.700000    0.000000   15.000000    0.000000
25%     22.985000    0.510000   31.000000    0.000000
50%     25.805000    7.510000   45.000000    0.000000
75%     28.497500   23.892500   55.000000    1.000000
max     46.580000  147.190000   64.000000    1.000000
Index(['row.names', 'sbp', 'tobacco', 'ldl', 'adiposity', 'famhist', 'typea',
       'obesity', 'alcohol', 'age', 'chd'],
      dtype='object')
               0       1        2        3        4        5       6    \
row.names        1       2        3        4        5        6       7
sbp            160     144      118      170      134      132     142
tobacco       12.0    0.01     0.08      7.5     13.6      6.2    4.05
ldl           5.73    4.41     3.48     6.41      3.5     6.47    3.38
adiposity    23.11   28.61    32.28    38.03    27.78    36.21    16.2
famhist    Present  Absent  Present  Present  Present  Present  Absent
typea           49      55       52       51       60       62      59
obesity       25.3   28.87    29.14    31.99    25.99    30.77   20.81
alcohol       97.2    2.06     3.81    24.26    57.34    14.14    2.62
age             52      63       46       58       49       45      38
chd              1       1        0        1        1        0       0

               7        8        9    ...      452      453     454     455  \
row.names        8        9       10  ...      454      455     456     457
sbp            114      114      132  ...      154      124     146     128
tobacco       4.08      0.0      0.0  ...     5.53      1.6    0.64    2.24
ldl           4.59     3.83      5.8  ...      3.2     7.22    4.82    2.83
adiposity     14.6     19.4    30.96  ...    28.81    39.68   28.02   26.48
famhist    Present  Present  Present  ...  Present  Present  Absent  Absent
typea           62       49       69  ...       61       36      60      48
obesity      23.11    24.86    30.11  ...    26.15     31.5   28.11   23.96
alcohol       6.72     2.49      0.0  ...    42.79      0.0    8.23   47.42
age             58       29       53  ...       42       51      39      27
chd              1        0        1  ...        0        1       1       1

               456     457     458     459     460      461
row.names      458     459     460     461     462      463
sbp            170     214     182     108     118      132
tobacco        0.4     0.4     4.2     3.0     5.4      0.0
ldl           4.11    5.98    4.41    1.59   11.61     4.82
adiposity    42.06   31.72    32.1   15.23   30.79    33.41
famhist    Present  Absent  Absent  Absent  Absent  Present
typea           56      64      52      40      64       62
obesity       33.1   28.45   28.61   20.09   27.35     14.7
alcohol       2.06     0.0   18.72   26.64   23.97      0.0
age             57      58      52      55      40       46
chd              0       0       1       0       0        1

[11 rows x 462 columns]
(462, 11)